site_name: Dynamic-Dependency-Injection
theme: flatly
markdown_extensions:
    - toc:
        permalink: True

pages:
- Home: index.md
- Injection: injection/index.md
- Creation: creation/index.md
- Resolver: resolver/index.md
- Optionals: optionals/index.md
- Projectinfos: projectinfos/index.md
- Infos: infos/index.md
- About: about.md
