site_name: Dynamic-Dependency-Injection
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True

pages:
- Home: index.md
- About: 
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
- Docu:
    - 'Nested Builder': 'docu/nested-builder.md'