site_name: Dynamic-Dependency-Injection
site_author: Sven Ruppert
google_analytics: ['UA-35462441-6', 'Dynamic-Dependency-Injection']

theme: flatly
markdown_extensions:
    - toc:
        permalink: True

pages:
- Home: index.md
- Injection: injection/index.md
- Creation: creation/index.md
- Resolver: resolver/index.md
- Optionals: optionals/index.md
- Projectinfos: projectinfos/index.md
- Infos: infos/index.md
- About: about.md
